# MDCA Demo VM SSH Configuration
# Generated by Terraform for VS Code Remote-SSH extension
# 
# To use this configuration:
# 1. Copy this content to your SSH config file: C:\Users\User\.ssh\config
# 2. Open VS Code
# 3. Install Remote-SSH extension if not already installed
# 4. Press Ctrl+Shift+P and select "Remote-SSH: Connect to Host"
# 5. Select "mdca-demo-vm-${suffix}" from the list
#
# Manual SSH connection:
# ssh mdca-demo-vm-${suffix}

Host mdca-demo-vm-${suffix}
    HostName ${vm_public_ip}
    User ${admin_user}
    IdentityFile C:/Users/User/.ssh/${private_key}
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    ServerAliveInterval 60
    ServerAliveCountMax 3
    
# Alternative host entry for direct IP connection
Host mdca-${suffix}
    HostName ${vm_public_ip}
    User ${admin_user}
    IdentityFile C:/Users/User/.ssh/${private_key}
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    ServerAliveInterval 60
    ServerAliveCountMax 3

# ================================================
# MDCA Demo VM Connection Details
# ================================================
# VM Name: mdca-demo-vm-${suffix}
# Public IP: ${vm_public_ip}
# Username: ${admin_user}
# SSH Key: C:/Users/User/.ssh/${private_key}
# 
# Quick Commands:
# - Connect: ssh mdca-demo-vm-${suffix}
# - Copy files: scp file.txt mdca-demo-vm-${suffix}:/tmp/
# - Port forward: ssh -L 8080:localhost:8080 mdca-demo-vm-${suffix}
# 
# VS Code Remote-SSH:
# - Install extension: ms-vscode-remote.remote-ssh
# - Connect via Command Palette: "Remote-SSH: Connect to Host"
# ================================================
